### ISSUE TITLE
Setting up relational database to at least store users' profiles and data

### ISSUE THREAD

**Issue by ChiefsBestPal** [SenecalRenaud/equipeBoucani-soen341project2023#10]
A database is needed for the basic user profiling system to be properly working; else one would have to locally store or use a custom way to encode raw text files to store information... A relational database will allow the app/website to connect components of the projects made with different technology and for different purpose easily. It is a core component in integration and to handle ever updating user data and eventually for any dedicated data that has a purpose in being classified.

**Comment by SenecalRenaud** [comment]
Done
