### ISSUE TITLE
Send emails when chosen for interview 

### ISSUE THREAD

**Issue by Spiratatoe** [SenecalRenaud/equipeBoucani-soen341project2023#2]
As a Job Seeker, I would like to receive an email notification if i get accepted for an interview

auto send emails if chosen for interview, 
will need to use the email set to the users account

**Comment by ozan1318** [comment]
Currently we have a functional email system that can send emails when an HTTP request is sent. This will be updated and integrated into the Firebase user system and to the user job application process.
