### ISSUE TITLE
Finish Implement edit and update operations for posts

### ISSUE THREAD

**Issue by ChiefsBestPal** [SenecalRenaud/equipeBoucani-soen341project2023#20]
As a user, employer or student, I would want to be able to delete or edit posts.

**Comment by ChiefsBestPal** [comment]
For now, root / any user will be able to do these operations. 

**Later on, they will be only accessible if the user ID of the comment/post/etc matches the logged in user's UID.**

**Comment by SenecalRenaud** [comment]
This was completed in sprint 2.
