### ISSUE TITLE
Implement Frontend into the current Backend to replace the debug frontend currently used

### ISSUE THREAD

**Issue by ozan1318** [SenecalRenaud/equipeBoucani-soen341project2023#23]
Currently the project launches to the experimental/debug frontend, this will be replaced by the frontend that Jack is working on. Jack's frontend needs to be integrated into the current working backend.

**Comment by Spiratatoe** [comment]
This was accomplished, slight things to maybe do in the future such as add more elements to main and to the nav bar, however the goal for this issue has been completed
