### ISSUE TITLE
Make a responsive job postings listing page (e.g. with flex or grid)

### ISSUE THREAD

**Issue by ChiefsBestPal** [SenecalRenaud/equipeBoucani-soen341project2023#30]

**Comment by ozan1318** [comment]
Basic version of this page with CRUD is available [in this branch](https://github.com/SenecalRenaud/equipeBoucani-soen341project2023/tree/Ozan-JobPosts_CRUD), needs proper front-end design and small fixes

**Comment by Spiratatoe** [comment]
When using the mobile button in developper mode the css gets kinda wonky vs when you just drag and size down, figure out why

**Comment by Spiratatoe** [comment]
the nav bar is also not pretty in mobile mode
