### ISSUE TITLE
Implement acceptance tests for stories

### ISSUE THREAD

**Issue by SenecalRenaud** [SenecalRenaud/equipeBoucani-soen341project2023#35]
Create tests procedures and link them to stories in the wiki
Using Selenium, write each test script
Make all tests run automatically using Travis (link tests to travis.yml file)

**Comment by ozan1318** [comment]
.travis.yml file is now ready to add tests into

**Comment by ozan1318** [comment]
Implemented acceptance test for Story 5 (Login) and Story 4 (Main Page)

**Comment by SenecalRenaud** [comment]
Latest commit finalized this issue
