### ISSUE TITLE
Make an "Apply to Job" page

### ISSUE THREAD

**Issue by ChiefsBestPal** [SenecalRenaud/equipeBoucani-soen341project2023#45]
As a user, I would like to be able to apply to jobs and upload cover letters, write notes and use my stored resume.

**Comment by Patrickriachi** [comment]
DONE on patrick'sUpdatedBranch. Routed as NavLink. Should be routed to job postings button

**Comment by Spiratatoe** [comment]
also did one, i guess use the better of the two
