### ISSUE TITLE
Make the website more professional looking

### ISSUE THREAD

**Issue by Spiratatoe** [SenecalRenaud/equipeBoucani-soen341project2023#49]
As a user, I would like to be able to trust the website I'm using.
This can be achieved though functionality but also first impressions and eye candy,
therefore, thew website must look as charming and professional as posible

**Comment by Spiratatoe** [comment]
Ways to achieve this : 
color choice 
information about the website 
convincing advertisement 
fancy animations
responsive design

**Comment by ChiefsBestPal** [comment]
It has been a while but I have made loading screens, error screens.

Jack has worked on the home page quite a bit and the overall page was UX reviewed in April 12th and April 13th Meetings (see wiki).

Closed
