### ISSUE TITLE
Create Main Page

### ISSUE THREAD

**Issue by Spiratatoe** [SenecalRenaud/equipeBoucani-soen341project2023#5]
As a user, I'd like there to be a main page where I can then navigate to any other page on the platform

have a highly informative but clean main page that serves as a hub for all other pages
Needs logo and name
Navbar
Login button
...

**Comment by Spiratatoe** [comment]
2 story points

**Comment by SenecalRenaud** [comment]
Main page is done and successfully links to other pages.
