### ISSUE TITLE
Bug: wrong user is shown after search

### ISSUE THREAD

**Issue by ozan1318** [SenecalRenaud/equipeBoucani-soen341project2023#61]
Bug shown in video. Website is on the latest version of Antoince's branch as of [this commit](https://github.com/SenecalRenaud/equipeBoucani-soen341project2023/commit/0840df9ca6c25facc9bb697e0cb9267fea55a759)

https://user-images.githubusercontent.com/89036827/229981372-50e5f4bc-e094-4310-8d7e-b5363190aee5.mp4

**Comment by ChiefsBestPal** [comment]
Works on my current version for my part. Remove all job postings and post some new ones, database may have had some changes and the backend API as well. @ozan1318
