### ISSUE TITLE
Bug: First job post not visible in My Job Postings page

### ISSUE THREAD

**Issue by ozan1318** [SenecalRenaud/equipeBoucani-soen341project2023#62]

**Comment by ozan1318** [comment]
fixed: wrong code was pushed, fixed with [this commit](https://github.com/SenecalRenaud/equipeBoucani-soen341project2023/commit/661f125e5bbfbaec49ad5251ac9dd3ec2c909777)

**Comment by ChiefsBestPal** [comment]
Youre welcome ;P 

lol
