### ISSUE TITLE
Bug: Navbar not centered, Sign In/Sign Up/Profile buttons not properly visible

### ISSUE THREAD

**Issue by ozan1318** [SenecalRenaud/equipeBoucani-soen341project2023#66]

**Comment by ozan1318** [comment]
Partially fixed with [this commit](https://github.com/SenecalRenaud/equipeBoucani-soen341project2023/commit/ade7d375a1e93c6663c488ca3f1dd92ab4a6c303)

> signin/signup/profile button not visible fixed, minor issue post-merge

**Comment by ChiefsBestPal** [comment]
This has been a recurring problem recently.  Frontend guys @Patrickriachi @Spiratatoe , when you have time please fix the styling for the navbar.

**Comment by Patrickriachi** [comment]
on patrick'sUpdatedBranch the navbar is fixed
