### ISSUE TITLE
Run Static Analysis and Linter on Backend Python code

### ISSUE THREAD

**Issue by ChiefsBestPal** [SenecalRenaud/equipeBoucani-soen341project2023#78]
Refactor backend python code based on libraries used to follow their respective convention, as well as PEP8.

**Comment by SenecalRenaud** [comment]
Latest commits:
https://github.com/SenecalRenaud/equipeBoucani-soen341project2023/commit/76275b4655a51a051b816d7d944d5cafb79c00ed
https://github.com/SenecalRenaud/equipeBoucani-soen341project2023/commit/3cedcdf838975bdea4de1d209222237f0c971b9a
